#!/usr/bin/env bash
# setup_pi.sh: set up a fresh Raspberry Pi OS machine (or any Debian/Ubuntu
# box) with my shell environment: dotfiles from this repo, CLI utilities,
# atuin, ble.sh, tmux, Tailscale, aider and Claude Code.
#
# Safe to re-run. Each step checks whether it is already done and skips it.
# It works on ARM (Pi) as well as x86 because everything comes from apt or an
# arch-aware installer.
#
# Usage, on the new machine as your normal user (needs sudo):
#   sudo apt update && sudo apt install -y git
#   git clone -b raspberry https://github.com/qemqemqem/utils.git ~/Dev/utils
#   bash ~/Dev/utils/bash/setup_pi.sh
#
# This script cannot do the following; the summary at the end lists them:
#   - copy ~/Dev/private_keys.sh (secrets are never stored in git)
#   - log in to Tailscale, atuin and Claude Code
set -euo pipefail

UTILS="$HOME/Dev/utils"
BASHRC_SRC="$UTILS/bash/.bashrc"

step() { printf '\n\033[1;36m==> %s\033[0m\n' "$*"; }
skip() { printf '    (already done: %s)\n' "$*"; }

[ "$EUID" -ne 0 ] || { echo "Run as your normal user, not root (it uses sudo itself)." >&2; exit 1; }
[ -f "$BASHRC_SRC" ] || { echo "Expected the utils repo at $UTILS (see Usage at the top)." >&2; exit 1; }

# Packages are grouped by what needs them.
APT_PACKAGES=(
  # basics
  git curl wget gnupg unzip rsync build-essential gawk
  # shell environment (.bashrc / .bash_aliases depend on these)
  tmux fzf direnv bat catimg jp2a fortune-mod fortunes-es translate-shell
  gridsite-clients trash-cli micro golang-go pipx npm
  # everyday utilities
  tig htop btop ncdu jq ripgrep fd-find tree lsof dnsutils git-delta shellcheck
)

step "Installing apt packages"
sudo apt-get update -qq
sudo DEBIAN_FRONTEND=noninteractive apt-get install -y -qq "${APT_PACKAGES[@]}"

step "Creating directories"
mkdir -p ~/Dev ~/Installs ~/Pictures/Art ~/.logs
touch ~/.logs/"bash-history-$(date +%F).log"

step "Linking dotfiles from $UTILS"
link() {  # link <target-in-repo> <path-in-home>
  if [ "$(readlink -f "$2")" = "$(readlink -f "$1")" ]; then skip "$2"; return; fi
  [ -e "$2" ] && mv -v "$2" "$2.pre-utils.$(date +%s)"
  ln -sv "$1" "$2"
}
link "$BASHRC_SRC" ~/.bashrc
link "$UTILS/.tmux.conf" ~/.tmux.conf

step "Placeholder for ~/Dev/private_keys.sh (sourced by .bashrc)"
if [ -f ~/Dev/private_keys.sh ]; then skip "private_keys.sh exists"; else
  printf '# Secrets (API keys etc.). Copy the real file from another machine.\n' > ~/Dev/private_keys.sh
  chmod 600 ~/Dev/private_keys.sh
  NEED_KEYS=1
fi

step "fzf key bindings (~/.fzf.bash, sourced by .bashrc)"
if [ -f ~/.fzf.bash ]; then skip ".fzf.bash"; else
  cat > ~/.fzf.bash <<'EOF'
# Generated by setup_pi.sh: apt's fzf bindings (Ctrl-R, Ctrl-T, Alt-C).
for f in /usr/share/doc/fzf/examples/key-bindings.bash /usr/share/bash-completion/completions/fzf; do
  [ -f "$f" ] && source "$f"
done
EOF
fi

step "atuin (shell history)"
if command -v atuin >/dev/null || [ -x ~/.atuin/bin/atuin ]; then skip "atuin"
elif apt-cache show atuin >/dev/null 2>&1; then sudo apt-get install -y -qq atuin
else curl --proto '=https' --tlsv1.2 -LsSf https://setup.atuin.sh | sh
fi

step "ble.sh (line editor, sourced by .bashrc)"
if [ -f ~/Installs/ble.sh/out/ble.sh ]; then skip "ble.sh"; else
  git clone --recursive --depth 1 --shallow-submodules https://github.com/akinomyoga/ble.sh.git ~/Installs/ble.sh
  make -C ~/Installs/ble.sh
fi

step "Tailscale"
if command -v tailscale >/dev/null; then skip "tailscale"; else
  # shellcheck disable=SC1091
  . /etc/os-release
  curl -fsSL "https://pkgs.tailscale.com/stable/$ID/$VERSION_CODENAME.noarmor.gpg" \
    | sudo tee /usr/share/keyrings/tailscale-archive-keyring.gpg >/dev/null
  curl -fsSL "https://pkgs.tailscale.com/stable/$ID/$VERSION_CODENAME.tailscale-keyring.list" \
    | sudo tee /etc/apt/sources.list.d/tailscale.list >/dev/null
  sudo apt-get update -qq && sudo apt-get install -y -qq tailscale
fi

step "aider"
if command -v aider >/dev/null || [ -x ~/.local/bin/aider ]; then skip "aider"; else
  # Plain `pipx install aider-chat` fails on Python 3.13 because of a pinned numpy;
  # aider-install provisions its own Python. It also appends a PATH line to
  # ~/.bashrc, which is this repo's file, so put the bashrc back afterwards.
  cp "$BASHRC_SRC" "$BASHRC_SRC.setup-bak"
  pipx install aider-install && ~/.local/bin/aider-install
  mv "$BASHRC_SRC.setup-bak" "$BASHRC_SRC"
fi

step "Claude Code"
if command -v claude >/dev/null || [ -x ~/.local/bin/claude ]; then skip "claude"; else
  curl -fsSL https://claude.ai/install.sh | bash
fi

if grep -qs "Raspberry Pi" /proc/device-tree/model; then
  step "Raspberry Pi tweaks"
  NM_CONF=/etc/NetworkManager/conf.d/99-wifi-powersave-off.conf
  if [ -f "$NM_CONF" ]; then skip "Wi-Fi power save off"; else
    # Pi Wi-Fi power saving caused DNS/connection drops mid-install (Oct 2026).
    printf '[connection]\nwifi.powersave = 2\n' | sudo tee "$NM_CONF" >/dev/null
    echo "    Wi-Fi power save disabled (applies on next reconnect)"
  fi
fi

step "Done"
echo
echo "Remaining manual steps:"
[ -n "${NEED_KEYS:-}" ] && echo "  - Copy the real ~/Dev/private_keys.sh from another machine (a placeholder was created)."
cat <<EOF
  - Tailscale:   sudo tailscale up
  - atuin sync:  atuin login        (optional)
  - Claude Code: claude             (logs in through a browser)
  - Open a new shell (or: exec bash -l) to pick everything up.

Pi + USB SSD: if the drive ever drops off (the site and SSH die, and kernel
I/O errors appear), disable UAS for it. Find its ID with lsusb, then append
  usb-storage.quirks=VVVV:PPPP:u
to /boot/firmware/cmdline.txt (keep it all on one line) and reboot.
EOF
